// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhmGQkr6h9f0vyw_6E02_rhb-nVkI8Omk',
    appId: '1:120713953249:web:2900e16032fd82a4b35ca0',
    messagingSenderId: '120713953249',
    projectId: 'presenfirebase',
    authDomain: 'presenfirebase.firebaseapp.com',
    storageBucket: 'presenfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzIIjJXqD6IPPxxuFheYRToL8K4Hu-ork',
    appId: '1:120713953249:android:930c0bd210575f77b35ca0',
    messagingSenderId: '120713953249',
    projectId: 'presenfirebase',
    storageBucket: 'presenfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVnImt9INIZ_IjXRDpV08htkO-JtLEDfc',
    appId: '1:120713953249:ios:e227ab177c116149b35ca0',
    messagingSenderId: '120713953249',
    projectId: 'presenfirebase',
    storageBucket: 'presenfirebase.firebasestorage.app',
    iosBundleId: 'com.example.prsenentaionFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVnImt9INIZ_IjXRDpV08htkO-JtLEDfc',
    appId: '1:120713953249:ios:e227ab177c116149b35ca0',
    messagingSenderId: '120713953249',
    projectId: 'presenfirebase',
    storageBucket: 'presenfirebase.firebasestorage.app',
    iosBundleId: 'com.example.prsenentaionFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhmGQkr6h9f0vyw_6E02_rhb-nVkI8Omk',
    appId: '1:120713953249:web:0f19a1c75683d9feb35ca0',
    messagingSenderId: '120713953249',
    projectId: 'presenfirebase',
    authDomain: 'presenfirebase.firebaseapp.com',
    storageBucket: 'presenfirebase.firebasestorage.app',
  );
}
